version: "3.8"

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      cache_from:
        - capfalc_django:dev
        - capfalc_django:latest
      dockerfile: ./compose/local/django/Dockerfile
    image: capfalc_django:dev
    container_name: django
    depends_on:
      - postgres
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
      - "3000:3000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: capfalc_postgres:latest
    container_name: postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  docs:
    image: capfalc_docs:dev
    container_name: docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./backend/docs:/docs
      - ./backend/config:/app/config
      - ./backend/capfalc:/app/capfalc
    ports:
      - "7000:7000"
