name: Backend tests

on: [push, pull_request]

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: pip install -r requirements/code_quality.txt
        working-directory: ./backend
      - run: flake8 . --config=setup.cfg --max-complexity=10
        working-directory: ./backend

  test_backend:
    needs: flake8
    env:
      POSTGRES_USER: "capfalc"
      POSTGRES_PASSWORD: ""
      POSTGRES_DB: "test_capfalc"
      POSTGRES_HOST_AUTH_METHOD: trust
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker-compose -f local.yml build
      # Ensure celerybeat does not crash due to non-existent tables
      - run: docker-compose -f local.yml run --rm django python backend/manage.py migrate
      - run: docker-compose -f local.yml up -d
      - run: docker-compose -f local.yml run -w /app/backend django mypy capfalc config --config=setup.cfg
      - run: docker-compose -f local.yml run django pytest backend/capfalc
