name: Deployement

on:
  push:
    branches: [master]

jobs:
  deployement:
    needs: [test_backend, test_frontend]
    env:
      POSTGRES_USER: "capfalc"
      POSTGRES_PASSWORD: ""
      POSTGRES_DB: "test_capfalc"
      POSTGRES_HOST_AUTH_METHOD: trust
      GROUP_NAME: "koena-sas"
      PROJECT_NAME: "capfalc"
      REGISTRY: "ghcr.io"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cp -r .envs/production_template .envs/.production
      - run: docker-compose -f production.yml build
      # Uncomment this to upload Docker image to Github registry
      # - name: Login to GitHub Packages Docker Registry
      #   uses: docker/login-action@v1
      #   with:
      #     registry: docker.pkg.github.com
      #     username: ${{ github.repository_owner }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      # - name: Tag the image before push
      #   run: docker tag capfalc_django:latest "${REGISTRY}/${GROUP_NAME}/${PROJECT_NAME}.latest"
      # - name: Pushing back the result
      #   run: docker push "${REGISTRY}/${GROUP_NAME}/${PROJECT_NAME}.latest"
